### ISSUE TITLE
Allow do define custom schema for column types

### ISSUE THREAD

**Issue by Horusiath** [fsprojects/ExcelProvider#40] opened 2017-02-17 12:46 UTC
It looks like at the current state `ExcelProvider<>` supports a very [limited](https://github.com/fsprojects/ExcelProvider/blob/master/src/ExcelProvider/ExcelProvider.fs#L56) set of data types, namely `float`, `bool`, `DateTime` (which sometimes is not recognized correctly) and `string`.

This issue brings two things:

1. Support more types, at least `double`, `decimal`, `int`, `int64` and options. Excels are often used in fields, where float precision is far to weak.
2. Idea borrowed from a [CsvProvider](http://fsharp.github.io/FSharp.Data/library/CsvProvider.html), which allows to define additional `Schema` property where types of columns can be specified manually (I found some cases where Date column is treated as float). It doesn't have to be as advanced as in CsvProvider, but something like `date,string, string, int option, decimal` would be a great relief.

**Comment by dsyme** [comment] 2018-09-12 12:46
Duplicate of #57

**Closed by dsyme** 2018-09-12 12:46 UTC
